# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee995cb7d6c6da96cca578587fb7f17c5ced3411983a660589d55a2115f49927049102a68c9ea2d335c5e10e0a5680f5947bc8c7a5c200018aa6f68d4d8e6679

test:
  secret_key_base: 6422963266d0031d6c9ed8c808c32b2b0ee67a1734ba4acf16fbd0071bcd230a9b163c76c356dffe1dce66cb5974977ca5e6d9c1c9f102a986df6c1eac64449c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
